allow_concurrent_steps: true
version: "2017-09-20"
pipeline:
  - id: build-server
    type: script
    overlay: ci/java11
    commands:
      - desc: Build server
        cmd: |
          cd $PWD/server
          ./gradlew zally-server:build
    cache:
      paths: [ ~/.gradle/caches, ~/.gradle/wrapper ]

  - id: web-ui
    type: script
    overlay: ci/nodejs-10
    commands:
      - desc: Build Web UI
        cmd: |
          cd $PWD/web-ui
          npm install -q ; npm test ; npm run build
    cache:
      paths: [ ~/.npm ]

  - id: build-and-push-images
    type: script
    env:
      DOCKER_HOST: "pierone.stups.zalan.do"
      DOCKER_TEAM: "pitchfork"
#    when:
#      branch: master
#    depends_on: [ all_of_the_above ]
    depends_on: [ ]
    commands:
      - desc: Building and pushing Zally Server
        cmd: |
          DOCKER_VERSION="${CDP_TARGET_BRANCH}-${CDP_TARGET_COMMIT_ID:0:8}-${CDP_TARGET_REPOSITORY_COUNTER}"
          cd server
          docker build -t "${DOCKER_HOST}/${DOCKER_TEAM}/zally:${DOCKER_VERSION}" .
          docker push "${DOCKER_HOST}/${DOCKER_TEAM}/zally:${DOCKER_VERSION}"

      - desc: Building and pushing Zally Web UI Dummy
        cmd: |
          DOCKER_VERSION="${CDP_TARGET_BRANCH}-${CDP_TARGET_COMMIT_ID:0:8}-${CDP_TARGET_REPOSITORY_COUNTER}"
          cd web-ui
          docker build -t "${DOCKER_HOST}/${DOCKER_TEAM}/zally-web-ui-dummy:${DOCKER_VERSION}" .
          docker push "${DOCKER_HOST}/${DOCKER_TEAM}/zally-web-ui-dummy:${DOCKER_VERSION}"
